//import { useNavigate } from "react-router-dom";

const lang = {
  en: {
    search: "Search",
    gptSearchPlaceHolder: "What would you like to watch today!!",
    start: "Play",
    info: "More Info",
    Now_Playing: "Now Playing",
    Popular: "Popular",
    Upcomming_Movies: "Upcomming Movies",
    Horror: "Horror",
    Sci_fi: "Sci-fi",
    signIn: "Sign In",
    signUp: "Sign Up",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    createPwd: "Create New Password",
    remember: "Remember Me",
    needHelp: "Need Help ?",
    newToNetflix: "New to Netflix?",
    signUpNow: "Sign Up Now.",
    signInNow: "Sign In Now.",
    alreadyUser: "Already a user?",
    Home: "Home",
    Tv_Shows: "Tv Shows",
    NewPopular: "New & Popular",
    My_List: "My List",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceHolder: "आज आप क्या देखना चाहेंगे!!",
    start: "शुरु",
    info: "और जानकारी",
    Now_Playing: "अब शुरू हैं",
    Popular: "लोकप्रिय",
    Upcomming_Movies: "आने वाली फिल्में",
    Horror: "डरावनी",
    Sci_fi: "विज्ञान - फाई",
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    fullName: "पूरा नाम",
    email: "ईमेल एड्रेस",
    password: "पासवर्ड",
    createPwd: "नया पासवर्ड बनाएं",
    remember: "याद रखें",
    needHelp: "आपको मदद चाहिए?",
    newToNetflix: "Netflix पर नए हैं?",
    signUpNow: "अभी साइन अप करें",
    signInNow: "अभी साइन इन करें",
    alreadyUser: "Netflix पर पहले से हैं?",
    Home: "Home",
    Tv_Shows: "टीवी शो",
    NewPopular: "नया एवं लोकप्रिय",
    My_List: "मेरी सूची",
  },
  spanish: {
    search: "buscar",
    gptSearchPlaceHolder: "Que te gustaría ver hoy!!",
    start: "Jugar",
    info: "Más información",
    Now_Playing: "Jugando ahora",
    Popular: "Popular",
    Upcomming_Movies: "Próximas películas",
    Horror: "Horror",
    Sci_fi: "Ciencia ficción",
    signIn: "Iniciar sesión",
    signUp: "Inscribirse",
    fullName: "Nombre completo",
    email: "Dirección de correo electrónico",
    createPwd: "Crear nueva contraseña",
    password: "Contraseña",
    remember: "Acuérdate de mí",
    needHelp: "¿Necesitas ayuda?",
    newToNetflix: "¿Nuevo en Netflix?",
    signUpNow: "Regístrate ahora.",
    signInNow: "Regístrate.",
    alreadyUser: "¿Ya eres usuario?",
    Home: "Home",
    Tv_Shows: "Programas de televisión",
    NewPopular: "Nueva y popular",
    My_List: "Mi lista",
  },
  fr: {
    search: "recherche",
    gptSearchPlaceHolder: "Qu’aimeriez-vous regarder aujourd’hui ?",
    start: "Jouer",
    info: "Plus d'informations",
    Now_Playing: "Lecture en cours",
    Popular: "Populaire",
    Upcomming_Movies: "Films à venir",
    Horror: "Horreur",
    Sci_fi: "science-fiction",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    fullName: "Nom et prénom",
    email: "Adresse e-mail",
    password: "Mot de passe",
    createPwd: "Créer un nouveau mot de passe",
    remember: "Souviens-toi de moi",
    needHelp: "Besoin d'aide?",
    newToNetflix: "Nouveau sur Netflix?",
    signUpNow: "S'inscrire maintenant.",
    signInNow: "Connectez vous maintenant.",
    alreadyUser: "Déjà utilisateur?",
    Home: "Home",
    Tv_Shows: "Émissions de télévision",
    NewPopular: "Nouveau et populaire",
    My_List: "Ma liste",
  },
};

export default lang;
